// <auto-generated />
using System;
using Hogwarts.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hogwarts.Infrastructure.Migrations
{
    [DbContext(typeof(HogwartsDbContext))]
    [Migration("20240729223321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hogwarts.Domain.Entities.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Animal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Founder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Houses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290"),
                            Animal = "Lion",
                            Element = "Fire",
                            Founder = "Godric Gryffindor",
                            Name = "Gryffindor"
                        },
                        new
                        {
                            Id = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7"),
                            Animal = "Badger",
                            Element = "Earth",
                            Founder = "Helga Hufflepuff",
                            Name = "Hufflepuff"
                        },
                        new
                        {
                            Id = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569"),
                            Animal = "Eagle",
                            Element = "Air",
                            Founder = "Rowena Ravenclaw",
                            Name = "Ravenclaw"
                        },
                        new
                        {
                            Id = new Guid("d35cdb01-f1bb-401d-b661-0069aa16176c"),
                            Animal = "Serpent",
                            Element = "Water",
                            Founder = "Salazar Slytherin",
                            Name = "Slytherin"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Pictures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ed9fb1c-5cc9-4d9b-9809-c9292c8fa5e6"),
                            Url = "https://picsum.photos/640/480/?image=915"
                        },
                        new
                        {
                            Id = new Guid("7dddb336-2d40-421f-bd23-aeb4bd47b275"),
                            Url = "https://picsum.photos/640/480/?image=590"
                        },
                        new
                        {
                            Id = new Guid("023950ff-1bb8-4635-b9ae-c37d5d587b92"),
                            Url = "https://picsum.photos/640/480/?image=135"
                        },
                        new
                        {
                            Id = new Guid("abb49858-6f42-4ee0-9c7c-408e44090790"),
                            Url = "https://picsum.photos/640/480/?image=277"
                        },
                        new
                        {
                            Id = new Guid("75b43082-c11e-4b9a-96f4-88c19c5d1fcb"),
                            Url = "https://picsum.photos/640/480/?image=364"
                        },
                        new
                        {
                            Id = new Guid("0e302370-ac2b-4066-9afb-686db6adb627"),
                            Url = "https://picsum.photos/640/480/?image=436"
                        },
                        new
                        {
                            Id = new Guid("b4ae69a9-7fc1-447f-8189-2c8fc80b750d"),
                            Url = "https://picsum.photos/640/480/?image=277"
                        },
                        new
                        {
                            Id = new Guid("dcdc5019-5916-46a4-bd50-e501a09722f5"),
                            Url = "https://picsum.photos/640/480/?image=126"
                        },
                        new
                        {
                            Id = new Guid("e20fe47d-2b62-4564-9fbf-ecc944843f1d"),
                            Url = "https://picsum.photos/640/480/?image=807"
                        },
                        new
                        {
                            Id = new Guid("86cc7eb4-689d-4805-bf90-fad3a53278c9"),
                            Url = "https://picsum.photos/640/480/?image=1002"
                        },
                        new
                        {
                            Id = new Guid("561b36f8-d4b3-4d6d-bc89-6c5a024f212d"),
                            Url = "https://picsum.photos/640/480/?image=639"
                        },
                        new
                        {
                            Id = new Guid("a0ef4cda-ba5d-4b65-97f3-ccd118a751a4"),
                            Url = "https://picsum.photos/640/480/?image=844"
                        },
                        new
                        {
                            Id = new Guid("09ae35e2-b068-4830-b0f9-b573d79ff838"),
                            Url = "https://picsum.photos/640/480/?image=1043"
                        },
                        new
                        {
                            Id = new Guid("094322d3-f0f0-4e3e-a729-be056e16eb3e"),
                            Url = "https://picsum.photos/640/480/?image=370"
                        },
                        new
                        {
                            Id = new Guid("a8015c92-03f4-4e23-88e7-3e672a460c5e"),
                            Url = "https://picsum.photos/640/480/?image=1068"
                        },
                        new
                        {
                            Id = new Guid("e634e74e-9e74-4f99-9a04-616f6a032ee3"),
                            Url = "https://picsum.photos/640/480/?image=484"
                        },
                        new
                        {
                            Id = new Guid("9aba3543-4227-4d0e-83a9-105d7e7857cb"),
                            Url = "https://picsum.photos/640/480/?image=381"
                        },
                        new
                        {
                            Id = new Guid("d109ecc7-353e-412a-a6ec-adb58ffb3149"),
                            Url = "https://picsum.photos/640/480/?image=821"
                        },
                        new
                        {
                            Id = new Guid("993e6cda-f6ed-4efd-94dd-88f2d60cd137"),
                            Url = "https://picsum.photos/640/480/?image=886"
                        },
                        new
                        {
                            Id = new Guid("2695afa2-2209-4719-8c6b-b2653bac3843"),
                            Url = "https://picsum.photos/640/480/?image=906"
                        },
                        new
                        {
                            Id = new Guid("37c74758-ba49-458f-9d81-cf57a2173d2c"),
                            Url = "https://picsum.photos/640/480/?image=625"
                        },
                        new
                        {
                            Id = new Guid("142025cc-de46-4997-be6e-c78da6e725ee"),
                            Url = "https://picsum.photos/640/480/?image=523"
                        },
                        new
                        {
                            Id = new Guid("86704e16-9f4f-44bc-90d2-b40f30938c28"),
                            Url = "https://picsum.photos/640/480/?image=681"
                        },
                        new
                        {
                            Id = new Guid("7360ca89-fd9a-4881-b81f-4f92537d6639"),
                            Url = "https://picsum.photos/640/480/?image=228"
                        },
                        new
                        {
                            Id = new Guid("1bdc080c-e2f3-47ab-a59a-52a78c36281e"),
                            Url = "https://picsum.photos/640/480/?image=360"
                        },
                        new
                        {
                            Id = new Guid("f4baf971-e748-4a49-8723-0089f8bf8252"),
                            Url = "https://picsum.photos/640/480/?image=1083"
                        },
                        new
                        {
                            Id = new Guid("214239d4-dc2b-4133-929d-950fe5b91f8b"),
                            Url = "https://picsum.photos/640/480/?image=291"
                        },
                        new
                        {
                            Id = new Guid("787afeea-6b77-433a-b624-bec108aee579"),
                            Url = "https://picsum.photos/640/480/?image=1068"
                        },
                        new
                        {
                            Id = new Guid("7e38c40b-e861-4a0f-b1ef-b22f905f5400"),
                            Url = "https://picsum.photos/640/480/?image=351"
                        },
                        new
                        {
                            Id = new Guid("28410601-64d6-4888-8a04-069804594cef"),
                            Url = "https://picsum.photos/640/480/?image=747"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Primitives.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("BloodStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PictureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.ToTable("Characters", (string)null);

                    b.HasDiscriminator().HasValue("Character");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.StudentSubject", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .IsUnique();

                    b.ToTable("Subject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("550536db-2a98-4fa4-890b-87e156f987b0"),
                            Description = "Deserunt blanditiis in illum adipisci.",
                            Name = "Arithmancy"
                        },
                        new
                        {
                            Id = new Guid("4d9113d0-6fbd-4752-a906-d499154fdc8e"),
                            Description = "Nemo rerum omnis quia similique est facere.",
                            Name = "Arithmancy"
                        },
                        new
                        {
                            Id = new Guid("9ef30af7-bea9-4636-9f74-7f14d041fb65"),
                            Description = "Odio voluptas ipsam consequatur assumenda neque soluta voluptatem.",
                            Name = "Potions"
                        },
                        new
                        {
                            Id = new Guid("ee1d1160-dafc-4999-a261-650430523835"),
                            Description = "Neque nemo itaque rerum eum labore.",
                            Name = "Divination"
                        },
                        new
                        {
                            Id = new Guid("c7974e1d-bedd-4222-aa5f-7c2f41840f87"),
                            Description = "Perspiciatis reprehenderit impedit id.",
                            Name = "Charms"
                        },
                        new
                        {
                            Id = new Guid("51ac0798-6578-4d07-a310-3f5922fb379f"),
                            Description = "Alias molestias exercitationem eos non.",
                            Name = "Transfiguration"
                        },
                        new
                        {
                            Id = new Guid("f278179e-943a-4994-ac2f-e8d1d3ef66bd"),
                            Description = "Distinctio vel voluptas eos explicabo fugiat quas dolore.",
                            Name = "History of Magic"
                        },
                        new
                        {
                            Id = new Guid("e55bb2fc-0e48-4340-beba-c8f32421b4d2"),
                            Description = "Repudiandae vero voluptas rerum esse ex enim deleniti.",
                            Name = "Arithmancy"
                        },
                        new
                        {
                            Id = new Guid("a2ea116f-337d-4fdf-8a8f-01adf62144ea"),
                            Description = "Voluptates officia perferendis dolores sint voluptatibus soluta et autem.",
                            Name = "Divination"
                        },
                        new
                        {
                            Id = new Guid("1cf04042-d970-4add-a6d2-c3bcb1b22455"),
                            Description = "Expedita dignissimos sed repudiandae architecto dolores.",
                            Name = "Potions"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.HasBaseType("Hogwarts.Domain.Entities.Primitives.Character");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.ToTable("Professors", (string)null);

                    b.HasDiscriminator().HasValue("Professor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0566e3d2-1da5-41c5-a402-40310b072e70"),
                            Age = 51,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1942, 12, 7, 12, 56, 44, 55, DateTimeKind.Utc).AddTicks(1044),
                            Description = "Dolorem et a expedita est voluptatum ut.",
                            FirstName = "Magdalena",
                            LastName = "Cortés",
                            PictureId = new Guid("7e38c40b-e861-4a0f-b1ef-b22f905f5400"),
                            SubjectId = new Guid("9ef30af7-bea9-4636-9f74-7f14d041fb65")
                        },
                        new
                        {
                            Id = new Guid("3c70970a-a90b-4e05-af09-65723274df16"),
                            Age = 41,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1949, 3, 7, 19, 43, 49, 828, DateTimeKind.Utc).AddTicks(8464),
                            Description = "Id odio qui et.",
                            FirstName = "Alejandro",
                            LastName = "Ferrer",
                            PictureId = new Guid("214239d4-dc2b-4133-929d-950fe5b91f8b"),
                            SubjectId = new Guid("4d9113d0-6fbd-4752-a906-d499154fdc8e")
                        },
                        new
                        {
                            Id = new Guid("e97eb981-df08-428e-8985-443ce96dfb8d"),
                            Age = 33,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1976, 7, 16, 13, 54, 7, 925, DateTimeKind.Utc).AddTicks(3779),
                            Description = "Quo voluptatem soluta eligendi dolor tenetur modi.",
                            FirstName = "Samuel",
                            LastName = "Ybarra",
                            PictureId = new Guid("787afeea-6b77-433a-b624-bec108aee579"),
                            SubjectId = new Guid("9ef30af7-bea9-4636-9f74-7f14d041fb65")
                        },
                        new
                        {
                            Id = new Guid("3da14e16-b562-44a1-bcf2-d3167154293c"),
                            Age = 46,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1951, 4, 15, 13, 21, 51, 685, DateTimeKind.Utc).AddTicks(7159),
                            Description = "Aut et est temporibus iusto voluptas eaque quia.",
                            FirstName = "Pilar",
                            LastName = "Casanova",
                            PictureId = new Guid("abb49858-6f42-4ee0-9c7c-408e44090790"),
                            SubjectId = new Guid("4d9113d0-6fbd-4752-a906-d499154fdc8e")
                        },
                        new
                        {
                            Id = new Guid("dcf8e90d-3630-4ec1-b7eb-f113fe74b043"),
                            Age = 51,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1935, 3, 5, 10, 5, 21, 56, DateTimeKind.Utc).AddTicks(2072),
                            Description = "Architecto adipisci beatae.",
                            FirstName = "Marcos",
                            LastName = "Argüello",
                            PictureId = new Guid("09ae35e2-b068-4830-b0f9-b573d79ff838"),
                            SubjectId = new Guid("1cf04042-d970-4add-a6d2-c3bcb1b22455")
                        },
                        new
                        {
                            Id = new Guid("bcd93706-d26c-41ea-8761-8aebbb46cc55"),
                            Age = 63,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1946, 10, 14, 15, 14, 25, 676, DateTimeKind.Utc).AddTicks(3771),
                            Description = "Adipisci velit odit aliquid ab consequatur.",
                            FirstName = "Rebeca",
                            LastName = "Carreón",
                            PictureId = new Guid("142025cc-de46-4997-be6e-c78da6e725ee"),
                            SubjectId = new Guid("f278179e-943a-4994-ac2f-e8d1d3ef66bd")
                        },
                        new
                        {
                            Id = new Guid("2d2cf8c7-9608-4b18-bd8e-78f50c33d09a"),
                            Age = 31,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1972, 3, 3, 15, 3, 12, 444, DateTimeKind.Utc).AddTicks(2021),
                            Description = "Non rem voluptas veniam nobis mollitia vitae.",
                            FirstName = "Carlota",
                            LastName = "Fuentes",
                            PictureId = new Guid("86704e16-9f4f-44bc-90d2-b40f30938c28"),
                            SubjectId = new Guid("c7974e1d-bedd-4222-aa5f-7c2f41840f87")
                        },
                        new
                        {
                            Id = new Guid("25f5723d-a9e7-4954-bf4b-9e6f4100652b"),
                            Age = 38,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1956, 3, 20, 1, 27, 55, 158, DateTimeKind.Utc).AddTicks(4283),
                            Description = "Assumenda delectus accusamus occaecati dolorem modi inventore rerum et.",
                            FirstName = "Rocío",
                            LastName = "Benítez",
                            PictureId = new Guid("561b36f8-d4b3-4d6d-bc89-6c5a024f212d"),
                            SubjectId = new Guid("9ef30af7-bea9-4636-9f74-7f14d041fb65")
                        },
                        new
                        {
                            Id = new Guid("f31ce936-9e9e-4b60-b77d-0619dfff1cb2"),
                            Age = 27,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1972, 7, 18, 6, 44, 8, 397, DateTimeKind.Utc).AddTicks(6026),
                            Description = "Minima debitis perferendis et exercitationem maxime illo.",
                            FirstName = "Hernán",
                            LastName = "Casarez",
                            PictureId = new Guid("28410601-64d6-4888-8a04-069804594cef"),
                            SubjectId = new Guid("c7974e1d-bedd-4222-aa5f-7c2f41840f87")
                        },
                        new
                        {
                            Id = new Guid("c6cfd637-ac07-40f0-ba9b-5ad29a81911b"),
                            Age = 58,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1927, 9, 16, 23, 31, 27, 85, DateTimeKind.Utc).AddTicks(3571),
                            Description = "Sint eos ea.",
                            FirstName = "Antonia",
                            LastName = "Arriaga",
                            PictureId = new Guid("7360ca89-fd9a-4881-b81f-4f92537d6639"),
                            SubjectId = new Guid("1cf04042-d970-4add-a6d2-c3bcb1b22455")
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Hogwarts.Domain.Entities.Primitives.Character");

                    b.Property<Guid?>("HouseId")
                        .HasColumnType("uuid");

                    b.HasIndex("HouseId");

                    b.ToTable("Students", (string)null);

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39c6dff2-edb7-41ea-999b-c58b9e28cd08"),
                            Age = 16,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(2006, 12, 31, 8, 47, 23, 228, DateTimeKind.Utc).AddTicks(4274),
                            Description = "Veritatis tempora eum fugit omnis.",
                            FirstName = "Marcos",
                            LastName = "Flórez",
                            PictureId = new Guid("abb49858-6f42-4ee0-9c7c-408e44090790"),
                            HouseId = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569")
                        },
                        new
                        {
                            Id = new Guid("59e33904-b1d9-421f-847b-fcd91a7928ee"),
                            Age = 12,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2010, 9, 30, 4, 58, 12, 961, DateTimeKind.Utc).AddTicks(8047),
                            Description = "Animi corporis fuga veritatis.",
                            FirstName = "César",
                            LastName = "Naranjo",
                            PictureId = new Guid("86704e16-9f4f-44bc-90d2-b40f30938c28"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("b6f6f473-4908-4bc5-987a-4ddea366ff65"),
                            Age = 15,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2008, 1, 20, 22, 55, 53, 826, DateTimeKind.Utc).AddTicks(2044),
                            Description = "Et et quo et ut eum quod dolorem magni nesciunt.",
                            FirstName = "Emilia",
                            LastName = "López",
                            PictureId = new Guid("7360ca89-fd9a-4881-b81f-4f92537d6639"),
                            HouseId = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569")
                        },
                        new
                        {
                            Id = new Guid("21674414-ede2-4dc4-b2ff-33716f0c4dc4"),
                            Age = 14,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(2004, 1, 20, 15, 50, 28, 24, DateTimeKind.Utc).AddTicks(435),
                            Description = "Cum nihil ducimus ab quia laborum.",
                            FirstName = "Lorenzo",
                            LastName = "Pedraza",
                            PictureId = new Guid("f4baf971-e748-4a49-8723-0089f8bf8252"),
                            HouseId = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569")
                        },
                        new
                        {
                            Id = new Guid("3442d3f2-79b0-416c-85ff-c1bd2b32431f"),
                            Age = 13,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(2002, 6, 22, 6, 57, 16, 13, DateTimeKind.Utc).AddTicks(433),
                            Description = "Voluptatibus aut culpa deleniti eum in.",
                            FirstName = "María del Carmen",
                            LastName = "Galindo",
                            PictureId = new Guid("dcdc5019-5916-46a4-bd50-e501a09722f5"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("6fc8a086-8b8a-4650-aa7c-9090546e9a7b"),
                            Age = 13,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(2002, 3, 8, 14, 9, 43, 875, DateTimeKind.Utc).AddTicks(3564),
                            Description = "Ut odit quam ducimus iste adipisci culpa.",
                            FirstName = "Jerónimo",
                            LastName = "Guzmán",
                            PictureId = new Guid("214239d4-dc2b-4133-929d-950fe5b91f8b"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("f1a30b59-bcc6-41c1-9d64-8e42be42f8f6"),
                            Age = 15,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2007, 7, 27, 5, 24, 19, 160, DateTimeKind.Utc).AddTicks(4206),
                            Description = "Et et maxime unde qui debitis aut voluptas.",
                            FirstName = "Nicolás",
                            LastName = "Malave",
                            PictureId = new Guid("e20fe47d-2b62-4564-9fbf-ecc944843f1d"),
                            HouseId = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569")
                        },
                        new
                        {
                            Id = new Guid("48e84ce6-9e1e-45d9-8e0f-8ae4dddfd161"),
                            Age = 11,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2010, 1, 9, 3, 5, 34, 984, DateTimeKind.Utc).AddTicks(7465),
                            Description = "Enim sapiente sit.",
                            FirstName = "Jorge Luis",
                            LastName = "Solís",
                            PictureId = new Guid("75b43082-c11e-4b9a-96f4-88c19c5d1fcb"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("0019faed-230e-4e8b-b822-9f05d12abf2c"),
                            Age = 17,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2001, 4, 17, 17, 6, 19, 825, DateTimeKind.Utc).AddTicks(9511),
                            Description = "Et dolores eaque harum consequuntur ratione inventore ullam qui.",
                            FirstName = "Rafael",
                            LastName = "Montemayor",
                            PictureId = new Guid("1ed9fb1c-5cc9-4d9b-9809-c9292c8fa5e6"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("79260a12-a269-4b6c-9d14-5ac6eb6896e8"),
                            Age = 13,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1998, 8, 24, 11, 14, 47, 45, DateTimeKind.Utc).AddTicks(6371),
                            Description = "Et ullam quibusdam deleniti maiores dolorem.",
                            FirstName = "Marisol",
                            LastName = "Ruelas",
                            PictureId = new Guid("094322d3-f0f0-4e3e-a729-be056e16eb3e"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("0399dc0d-f475-46f7-af7a-1b3fcf045b13"),
                            Age = 13,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2009, 2, 13, 3, 1, 15, 589, DateTimeKind.Utc).AddTicks(8833),
                            Description = "Modi commodi blanditiis.",
                            FirstName = "Rodrigo",
                            LastName = "Vigil",
                            PictureId = new Guid("a0ef4cda-ba5d-4b65-97f3-ccd118a751a4"),
                            HouseId = new Guid("cc1ff1df-9e44-4152-9b76-af1785201569")
                        },
                        new
                        {
                            Id = new Guid("ba315104-b3cf-4b1a-b0cf-a5581db39d86"),
                            Age = 16,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2006, 5, 20, 10, 48, 44, 486, DateTimeKind.Utc).AddTicks(9251),
                            Description = "Est molestias optio.",
                            FirstName = "Ana María",
                            LastName = "Ceja",
                            PictureId = new Guid("b4ae69a9-7fc1-447f-8189-2c8fc80b750d"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("5b46a625-445c-4b28-8c26-5d16001f82e6"),
                            Age = 12,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2005, 1, 1, 8, 1, 14, 202, DateTimeKind.Utc).AddTicks(9802),
                            Description = "Iure sit cupiditate eum sapiente.",
                            FirstName = "Mateo",
                            LastName = "Urrutia",
                            PictureId = new Guid("28410601-64d6-4888-8a04-069804594cef"),
                            HouseId = new Guid("d35cdb01-f1bb-401d-b661-0069aa16176c")
                        },
                        new
                        {
                            Id = new Guid("7798cb8b-b94a-46e2-9d43-fa158e7db8a4"),
                            Age = 13,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2000, 1, 1, 9, 29, 49, 475, DateTimeKind.Utc).AddTicks(9362),
                            Description = "Ipsam consequatur explicabo pariatur perspiciatis.",
                            FirstName = "Carlota",
                            LastName = "Tejada",
                            PictureId = new Guid("86cc7eb4-689d-4805-bf90-fad3a53278c9"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("916e4d8a-08e4-4f5a-8e70-8436aff32b3a"),
                            Age = 17,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1995, 2, 15, 23, 8, 18, 854, DateTimeKind.Utc).AddTicks(8922),
                            Description = "Voluptas laboriosam et nulla sed voluptatem nisi.",
                            FirstName = "Alicia",
                            LastName = "Cruz",
                            PictureId = new Guid("142025cc-de46-4997-be6e-c78da6e725ee"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("92af5af1-5429-4c7d-ad4d-13dd1f51205e"),
                            Age = 13,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(2000, 12, 26, 3, 19, 59, 423, DateTimeKind.Utc).AddTicks(4108),
                            Description = "Voluptatem ipsam itaque iste nulla ullam nostrum natus.",
                            FirstName = "Federico",
                            LastName = "Almonte",
                            PictureId = new Guid("09ae35e2-b068-4830-b0f9-b573d79ff838"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("ec417b3f-5048-44b4-8ebd-1165d90f5ad7"),
                            Age = 12,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2005, 1, 14, 16, 2, 51, 66, DateTimeKind.Utc).AddTicks(7611),
                            Description = "Cum et tempore consectetur ipsum alias quaerat.",
                            FirstName = "Barbara",
                            LastName = "Rosado",
                            PictureId = new Guid("0e302370-ac2b-4066-9afb-686db6adb627"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("b623df1b-ba1a-4166-9c35-b59c4f735f0b"),
                            Age = 12,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2007, 4, 6, 6, 30, 43, 866, DateTimeKind.Utc).AddTicks(5136),
                            Description = "Magni et nisi sed in.",
                            FirstName = "Vicente",
                            LastName = "Ávila",
                            PictureId = new Guid("787afeea-6b77-433a-b624-bec108aee579"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        },
                        new
                        {
                            Id = new Guid("222cbc22-7e5a-486d-9a71-36593669f618"),
                            Age = 12,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2004, 9, 22, 21, 18, 1, 427, DateTimeKind.Utc).AddTicks(9554),
                            Description = "Quos amet eligendi commodi fugit recusandae dolores aut aut.",
                            FirstName = "Caridad",
                            LastName = "Vázquez",
                            PictureId = new Guid("d109ecc7-353e-412a-a6ec-adb58ffb3149"),
                            HouseId = new Guid("fdb80638-8219-42a3-8434-a4ed5a8e6290")
                        },
                        new
                        {
                            Id = new Guid("854d1fd6-ac3d-42e7-a4c5-17f5c14a94de"),
                            Age = 14,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2000, 9, 25, 23, 27, 53, 707, DateTimeKind.Utc).AddTicks(3014),
                            Description = "Quis cupiditate aliquid.",
                            FirstName = "María Elena",
                            LastName = "Lebrón",
                            PictureId = new Guid("2695afa2-2209-4719-8c6b-b2653bac3843"),
                            HouseId = new Guid("d2ad1b4a-c1ed-47f7-bfc2-feb2a6782bc7")
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Primitives.Character", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Picture", "Picture")
                        .WithOne("Character")
                        .HasForeignKey("Hogwarts.Domain.Entities.Primitives.Character", "PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.StudentSubject", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Domain.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Professor", "Professor")
                        .WithOne("Subject")
                        .HasForeignKey("Hogwarts.Domain.Entities.Subject", "ProfessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Primitives.Character", null)
                        .WithOne()
                        .HasForeignKey("Hogwarts.Domain.Entities.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.House", "House")
                        .WithMany("Students")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hogwarts.Domain.Entities.Primitives.Character", null)
                        .WithOne()
                        .HasForeignKey("Hogwarts.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.House", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Picture", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
