// <auto-generated />
using System;
using Hogwarts.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hogwarts.Infrastructure.Migrations
{
    [DbContext(typeof(HogwartsDbContext))]
    [Migration("20240730000907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hogwarts.Domain.Entities.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Animal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Founder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Houses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd"),
                            Animal = "Lion",
                            Element = "Fire",
                            Founder = "Godric Gryffindor",
                            Name = "Gryffindor"
                        },
                        new
                        {
                            Id = new Guid("0d046f3c-132c-4600-83c4-dc8ab34032b1"),
                            Animal = "Badger",
                            Element = "Earth",
                            Founder = "Helga Hufflepuff",
                            Name = "Hufflepuff"
                        },
                        new
                        {
                            Id = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9"),
                            Animal = "Eagle",
                            Element = "Air",
                            Founder = "Rowena Ravenclaw",
                            Name = "Ravenclaw"
                        },
                        new
                        {
                            Id = new Guid("ba18e1d7-82d6-4e6e-b17a-35e390ceec86"),
                            Animal = "Serpent",
                            Element = "Water",
                            Founder = "Salazar Slytherin",
                            Name = "Slytherin"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Pictures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fc67442-7ece-44b1-9013-28bd59fe28f6"),
                            Url = "https://picsum.photos/640/480/?image=991"
                        },
                        new
                        {
                            Id = new Guid("1fa61d94-befb-4a05-aa4b-38e281b631ee"),
                            Url = "https://picsum.photos/640/480/?image=62"
                        },
                        new
                        {
                            Id = new Guid("97876e18-9e16-435c-981d-7e730633d205"),
                            Url = "https://picsum.photos/640/480/?image=662"
                        },
                        new
                        {
                            Id = new Guid("dd759bde-0501-4a41-83f7-58212a099c72"),
                            Url = "https://picsum.photos/640/480/?image=423"
                        },
                        new
                        {
                            Id = new Guid("10f0c552-2db8-4df1-beac-cf01d32af47e"),
                            Url = "https://picsum.photos/640/480/?image=373"
                        },
                        new
                        {
                            Id = new Guid("0de5fd33-50d8-4aec-a5da-15773aed5520"),
                            Url = "https://picsum.photos/640/480/?image=525"
                        },
                        new
                        {
                            Id = new Guid("683cc819-be69-43a7-b266-b599139cc1ca"),
                            Url = "https://picsum.photos/640/480/?image=88"
                        },
                        new
                        {
                            Id = new Guid("2a964815-59b1-49b8-b3ad-6dc59dd9acf8"),
                            Url = "https://picsum.photos/640/480/?image=573"
                        },
                        new
                        {
                            Id = new Guid("f8843611-6b34-47ba-a709-7dc5ddadb766"),
                            Url = "https://picsum.photos/640/480/?image=425"
                        },
                        new
                        {
                            Id = new Guid("10857bf8-bb93-4baa-8d58-4af63904fa80"),
                            Url = "https://picsum.photos/640/480/?image=943"
                        },
                        new
                        {
                            Id = new Guid("97f64641-0e7b-4690-acc8-9b935b315e12"),
                            Url = "https://picsum.photos/640/480/?image=206"
                        },
                        new
                        {
                            Id = new Guid("6cca7071-6bd0-40fd-9d37-971341ff01d8"),
                            Url = "https://picsum.photos/640/480/?image=371"
                        },
                        new
                        {
                            Id = new Guid("bbec7b32-c39f-4a6e-9cbb-149d43d8ee8e"),
                            Url = "https://picsum.photos/640/480/?image=445"
                        },
                        new
                        {
                            Id = new Guid("3daa51e5-934b-477c-a063-86654a15880d"),
                            Url = "https://picsum.photos/640/480/?image=850"
                        },
                        new
                        {
                            Id = new Guid("64f8d0c1-86da-4efc-8fad-1d4f545daa35"),
                            Url = "https://picsum.photos/640/480/?image=475"
                        },
                        new
                        {
                            Id = new Guid("cc9aa96e-5359-470f-92b8-f0bc01ddd4c1"),
                            Url = "https://picsum.photos/640/480/?image=87"
                        },
                        new
                        {
                            Id = new Guid("140ed3e5-b17a-45fe-bac9-7833930af2ea"),
                            Url = "https://picsum.photos/640/480/?image=570"
                        },
                        new
                        {
                            Id = new Guid("84e8aa2e-fac5-4cf3-8086-2b2bd48a419c"),
                            Url = "https://picsum.photos/640/480/?image=593"
                        },
                        new
                        {
                            Id = new Guid("864ead2b-694a-4e41-b479-b99b6fea46cf"),
                            Url = "https://picsum.photos/640/480/?image=200"
                        },
                        new
                        {
                            Id = new Guid("398fd7c9-f366-4f5e-af23-7abbe3fafee4"),
                            Url = "https://picsum.photos/640/480/?image=338"
                        },
                        new
                        {
                            Id = new Guid("078bb06e-d3af-4d6a-b7eb-524dab18dc5b"),
                            Url = "https://picsum.photos/640/480/?image=644"
                        },
                        new
                        {
                            Id = new Guid("4b19ab10-36dd-4776-96db-ca100408764b"),
                            Url = "https://picsum.photos/640/480/?image=1037"
                        },
                        new
                        {
                            Id = new Guid("382f477a-eea7-4992-9d70-6f95e6e882a1"),
                            Url = "https://picsum.photos/640/480/?image=629"
                        },
                        new
                        {
                            Id = new Guid("0163e086-1bb6-4cc9-baf5-8391a675acdf"),
                            Url = "https://picsum.photos/640/480/?image=972"
                        },
                        new
                        {
                            Id = new Guid("68e76832-7e4b-45ff-8ec1-50e7c7d4215f"),
                            Url = "https://picsum.photos/640/480/?image=27"
                        },
                        new
                        {
                            Id = new Guid("d8d3d1ac-6e91-45f4-85c5-82211b426733"),
                            Url = "https://picsum.photos/640/480/?image=736"
                        },
                        new
                        {
                            Id = new Guid("694366fc-f320-4cc8-9b40-d09b9c0ed507"),
                            Url = "https://picsum.photos/640/480/?image=372"
                        },
                        new
                        {
                            Id = new Guid("d494ce78-8b59-4e99-80f4-0846539056b4"),
                            Url = "https://picsum.photos/640/480/?image=193"
                        },
                        new
                        {
                            Id = new Guid("e8b34fde-2816-4264-b1aa-947029515186"),
                            Url = "https://picsum.photos/640/480/?image=349"
                        },
                        new
                        {
                            Id = new Guid("91460151-76f4-4b1a-ab80-070a55323d73"),
                            Url = "https://picsum.photos/640/480/?image=256"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Primitives.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("BloodStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PictureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.ToTable("Characters", (string)null);

                    b.HasDiscriminator().HasValue("Character");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.StudentSubject", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .IsUnique();

                    b.ToTable("Subject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d32f6bb-584c-4c78-ab1b-1106e9723770"),
                            Description = "Possimus quibusdam consequatur veniam et illo.",
                            Name = "Flying"
                        },
                        new
                        {
                            Id = new Guid("efc43e2e-aae5-4167-afe7-684db0701dfd"),
                            Description = "Culpa amet magnam iusto aut.",
                            Name = "Flying"
                        },
                        new
                        {
                            Id = new Guid("d22da823-c93e-4320-be3d-e7bcc5896ac6"),
                            Description = "Eum excepturi fugit odit suscipit sint.",
                            Name = "Defense Against the Dark Arts"
                        },
                        new
                        {
                            Id = new Guid("a0a6ddf4-bc6c-4e7d-808c-6437ff2de44d"),
                            Description = "Non vel qui enim et vero sapiente et doloremque voluptatem.",
                            Name = "Astronomy"
                        },
                        new
                        {
                            Id = new Guid("f115bf2c-63c2-4266-aac2-0963099eefa0"),
                            Description = "Autem autem velit nesciunt.",
                            Name = "History of Magic"
                        },
                        new
                        {
                            Id = new Guid("2ca29bdd-5162-436a-b593-ec2e8e1a8b87"),
                            Description = "Vero magnam similique et aut debitis dolor dolore libero dolore.",
                            Name = "Arithmancy"
                        },
                        new
                        {
                            Id = new Guid("ac2fcd53-6914-48cf-bd8d-8fb0ab714918"),
                            Description = "Eum aliquid soluta consequatur enim quisquam reiciendis.",
                            Name = "Divination"
                        },
                        new
                        {
                            Id = new Guid("d7d4fe9b-a7e5-486f-a905-457f48b5c4b3"),
                            Description = "Sunt officia ducimus doloremque temporibus.",
                            Name = "Potions"
                        },
                        new
                        {
                            Id = new Guid("73869e37-b342-43a9-b5cd-01bd231ba809"),
                            Description = "Ab nihil reprehenderit ut id rerum aliquid iusto iure qui.",
                            Name = "Defense Against the Dark Arts"
                        },
                        new
                        {
                            Id = new Guid("76f6e76f-6fad-49ef-b1ba-5aa85e64d1a1"),
                            Description = "Eligendi voluptatum quas voluptatem consequatur illum et perferendis.",
                            Name = "Defense Against the Dark Arts"
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.HasBaseType("Hogwarts.Domain.Entities.Primitives.Character");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.ToTable("Professors", (string)null);

                    b.HasDiscriminator().HasValue("Professor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97430eed-52cf-4649-b7dc-f8cd660c4688"),
                            Age = 35,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1964, 1, 16, 22, 12, 48, 735, DateTimeKind.Utc).AddTicks(3262),
                            Description = "Et quae officia aliquid consectetur repudiandae nam quod quod.",
                            FirstName = "Sara",
                            LastName = "Trujillo",
                            PictureId = new Guid("1fa61d94-befb-4a05-aa4b-38e281b631ee"),
                            SubjectId = new Guid("d22da823-c93e-4320-be3d-e7bcc5896ac6")
                        },
                        new
                        {
                            Id = new Guid("63eae216-e964-4fdd-9f1a-d0ad28fa4b03"),
                            Age = 65,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1906, 7, 8, 14, 2, 4, 985, DateTimeKind.Utc).AddTicks(1469),
                            Description = "Cupiditate id est sint eos est molestiae.",
                            FirstName = "Lorenzo",
                            LastName = "Páez",
                            PictureId = new Guid("382f477a-eea7-4992-9d70-6f95e6e882a1"),
                            SubjectId = new Guid("ac2fcd53-6914-48cf-bd8d-8fb0ab714918")
                        },
                        new
                        {
                            Id = new Guid("176cd48e-a995-4351-a734-9d4e8df4f529"),
                            Age = 53,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1938, 11, 14, 16, 3, 22, 488, DateTimeKind.Utc).AddTicks(3476),
                            Description = "Repellendus praesentium similique excepturi velit sunt velit explicabo dolores.",
                            FirstName = "Eva",
                            LastName = "Prieto",
                            PictureId = new Guid("bbec7b32-c39f-4a6e-9cbb-149d43d8ee8e"),
                            SubjectId = new Guid("ac2fcd53-6914-48cf-bd8d-8fb0ab714918")
                        },
                        new
                        {
                            Id = new Guid("4158ebab-c272-4139-9e6f-52079e0e02ba"),
                            Age = 41,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1982, 7, 13, 16, 6, 59, 102, DateTimeKind.Utc).AddTicks(8349),
                            Description = "Dignissimos quisquam velit eligendi modi dicta sequi.",
                            FirstName = "Ana María",
                            LastName = "Raya",
                            PictureId = new Guid("97876e18-9e16-435c-981d-7e730633d205"),
                            SubjectId = new Guid("d7d4fe9b-a7e5-486f-a905-457f48b5c4b3")
                        },
                        new
                        {
                            Id = new Guid("80c28916-037b-42c3-9764-51b03ffda119"),
                            Age = 64,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1898, 12, 23, 1, 12, 56, 206, DateTimeKind.Utc).AddTicks(230),
                            Description = "Dignissimos suscipit est explicabo.",
                            FirstName = "Conchita",
                            LastName = "Tamez",
                            PictureId = new Guid("10857bf8-bb93-4baa-8d58-4af63904fa80"),
                            SubjectId = new Guid("efc43e2e-aae5-4167-afe7-684db0701dfd")
                        },
                        new
                        {
                            Id = new Guid("a31691e7-548c-4025-8080-64f61e8e51db"),
                            Age = 49,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(1949, 10, 13, 5, 17, 0, 442, DateTimeKind.Utc).AddTicks(663),
                            Description = "Officia quas ipsa nihil error nesciunt tempora.",
                            FirstName = "Lucía",
                            LastName = "Banda",
                            PictureId = new Guid("078bb06e-d3af-4d6a-b7eb-524dab18dc5b"),
                            SubjectId = new Guid("76f6e76f-6fad-49ef-b1ba-5aa85e64d1a1")
                        },
                        new
                        {
                            Id = new Guid("1086c854-f019-46d3-9afb-c2f563990f76"),
                            Age = 60,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(1915, 9, 29, 1, 35, 5, 301, DateTimeKind.Utc).AddTicks(6139),
                            Description = "Est voluptas optio harum animi amet assumenda et.",
                            FirstName = "Elvira",
                            LastName = "Razo",
                            PictureId = new Guid("0de5fd33-50d8-4aec-a5da-15773aed5520"),
                            SubjectId = new Guid("efc43e2e-aae5-4167-afe7-684db0701dfd")
                        },
                        new
                        {
                            Id = new Guid("4ea09390-2361-4d43-91e4-c0b3630fb144"),
                            Age = 57,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1924, 1, 11, 3, 58, 34, 62, DateTimeKind.Utc).AddTicks(541),
                            Description = "Perferendis sint quia in nihil id.",
                            FirstName = "Laura",
                            LastName = "Ferrer",
                            PictureId = new Guid("91460151-76f4-4b1a-ab80-070a55323d73"),
                            SubjectId = new Guid("d22da823-c93e-4320-be3d-e7bcc5896ac6")
                        },
                        new
                        {
                            Id = new Guid("11793a82-e532-4d72-acca-99279c890de7"),
                            Age = 44,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1938, 12, 4, 2, 18, 53, 927, DateTimeKind.Utc).AddTicks(9901),
                            Description = "Enim hic veniam.",
                            FirstName = "Beatriz",
                            LastName = "Naranjo",
                            PictureId = new Guid("864ead2b-694a-4e41-b479-b99b6fea46cf"),
                            SubjectId = new Guid("9d32f6bb-584c-4c78-ab1b-1106e9723770")
                        },
                        new
                        {
                            Id = new Guid("e2711673-9c97-417f-ae17-b81c6ac6b95f"),
                            Age = 45,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1945, 2, 21, 6, 8, 33, 519, DateTimeKind.Utc).AddTicks(2557),
                            Description = "Nihil numquam quos consequuntur itaque ullam est omnis.",
                            FirstName = "Micaela",
                            LastName = "Montes",
                            PictureId = new Guid("dd759bde-0501-4a41-83f7-58212a099c72"),
                            SubjectId = new Guid("2ca29bdd-5162-436a-b593-ec2e8e1a8b87")
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Hogwarts.Domain.Entities.Primitives.Character");

                    b.Property<Guid?>("HouseId")
                        .HasColumnType("uuid");

                    b.HasIndex("HouseId");

                    b.ToTable("Students", (string)null);

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("202b121c-512d-45c2-a3a9-0491e9c8e2d6"),
                            Age = 12,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2000, 12, 31, 15, 17, 24, 302, DateTimeKind.Utc).AddTicks(8242),
                            Description = "Omnis excepturi est et aliquid delectus sint eum atque.",
                            FirstName = "Gloria",
                            LastName = "de Anda",
                            PictureId = new Guid("140ed3e5-b17a-45fe-bac9-7833930af2ea"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("cdc117f6-8807-4014-9cd5-f25d5ffdb738"),
                            Age = 12,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2005, 1, 8, 13, 56, 50, 965, DateTimeKind.Utc).AddTicks(7444),
                            Description = "A quaerat quae autem doloremque et.",
                            FirstName = "Ana María",
                            LastName = "Tamayo",
                            PictureId = new Guid("864ead2b-694a-4e41-b479-b99b6fea46cf"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("37ab4aa0-2213-4c89-a025-7097cbad2cb2"),
                            Age = 13,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(2002, 11, 4, 10, 22, 16, 466, DateTimeKind.Utc).AddTicks(461),
                            Description = "Dolor aspernatur consequuntur rerum laboriosam quas sed ut natus nobis.",
                            FirstName = "Gonzalo",
                            LastName = "Granados",
                            PictureId = new Guid("bbec7b32-c39f-4a6e-9cbb-149d43d8ee8e"),
                            HouseId = new Guid("ba18e1d7-82d6-4e6e-b17a-35e390ceec86")
                        },
                        new
                        {
                            Id = new Guid("1346719a-a3d4-4e6a-9399-e97ee32325d7"),
                            Age = 13,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2001, 4, 9, 2, 20, 25, 115, DateTimeKind.Utc).AddTicks(7700),
                            Description = "Est facere harum qui necessitatibus dolor et cupiditate enim.",
                            FirstName = "Olivia",
                            LastName = "Raya",
                            PictureId = new Guid("91460151-76f4-4b1a-ab80-070a55323d73"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("c95d0700-0b33-4b9d-a8f1-fa3f6d1adadf"),
                            Age = 11,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2004, 5, 4, 19, 28, 10, 548, DateTimeKind.Utc).AddTicks(5134),
                            Description = "Enim eius non.",
                            FirstName = "Mariana",
                            LastName = "Barajas",
                            PictureId = new Guid("d494ce78-8b59-4e99-80f4-0846539056b4"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("ea979c96-912b-42a7-ba85-a844e3b71a0a"),
                            Age = 11,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(2009, 2, 7, 10, 14, 46, 329, DateTimeKind.Utc).AddTicks(5760),
                            Description = "Voluptatibus sint in ipsum perspiciatis et quam autem quisquam.",
                            FirstName = "Emilio",
                            LastName = "Concepción",
                            PictureId = new Guid("6fc67442-7ece-44b1-9013-28bd59fe28f6"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("8ddd6da0-a0aa-4427-984a-cfeaa21dce87"),
                            Age = 13,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2002, 3, 27, 11, 52, 46, 228, DateTimeKind.Utc).AddTicks(4286),
                            Description = "Magnam libero ratione iusto.",
                            FirstName = "Jorge",
                            LastName = "Guevara",
                            PictureId = new Guid("84e8aa2e-fac5-4cf3-8086-2b2bd48a419c"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("2371887a-7d5b-40c0-8cb9-5113ea02edba"),
                            Age = 16,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(2007, 11, 27, 22, 34, 27, 454, DateTimeKind.Utc).AddTicks(8823),
                            Description = "Corrupti mollitia dignissimos ad.",
                            FirstName = "Ramona",
                            LastName = "Almonte",
                            PictureId = new Guid("398fd7c9-f366-4f5e-af23-7abbe3fafee4"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("648b2598-956b-4b90-8df7-43a5657dfff1"),
                            Age = 14,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2001, 10, 14, 8, 2, 27, 469, DateTimeKind.Utc).AddTicks(3521),
                            Description = "At et aliquid.",
                            FirstName = "Jorge Luis",
                            LastName = "Esparza",
                            PictureId = new Guid("1fa61d94-befb-4a05-aa4b-38e281b631ee"),
                            HouseId = new Guid("ba18e1d7-82d6-4e6e-b17a-35e390ceec86")
                        },
                        new
                        {
                            Id = new Guid("bccbedd2-e0b6-463c-ac5c-f232aaf90883"),
                            Age = 16,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2005, 12, 18, 11, 14, 59, 13, DateTimeKind.Utc).AddTicks(1810),
                            Description = "Adipisci omnis aut et.",
                            FirstName = "Gabriel",
                            LastName = "Valencia",
                            PictureId = new Guid("694366fc-f320-4cc8-9b40-d09b9c0ed507"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("bd7327d2-fe58-4abc-a28d-3eb7a03fe60b"),
                            Age = 13,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(1999, 4, 12, 15, 59, 8, 675, DateTimeKind.Utc).AddTicks(3453),
                            Description = "Accusantium voluptatum pariatur ut soluta architecto.",
                            FirstName = "María Soledad",
                            LastName = "Zarate",
                            PictureId = new Guid("cc9aa96e-5359-470f-92b8-f0bc01ddd4c1"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("ac93d46a-f10b-4ba5-87f3-27720c169ee1"),
                            Age = 14,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(1999, 3, 19, 2, 1, 0, 788, DateTimeKind.Utc).AddTicks(9534),
                            Description = "Repellendus eveniet sit iure totam nesciunt.",
                            FirstName = "Rosa",
                            LastName = "Uribe",
                            PictureId = new Guid("4b19ab10-36dd-4776-96db-ca100408764b"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("15b6abcd-1cb7-4b5f-a960-bd8cadbbf151"),
                            Age = 14,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(2006, 1, 1, 2, 18, 19, 984, DateTimeKind.Utc).AddTicks(3876),
                            Description = "Incidunt commodi vero commodi aperiam modi qui.",
                            FirstName = "María Teresa",
                            LastName = "Alicea",
                            PictureId = new Guid("382f477a-eea7-4992-9d70-6f95e6e882a1"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("fad54602-5fb5-40e5-8c21-d30b98861c30"),
                            Age = 14,
                            BloodStatus = 1,
                            DateOfBirth = new DateTime(2006, 3, 5, 6, 46, 57, 169, DateTimeKind.Utc).AddTicks(1314),
                            Description = "Illo aperiam omnis quaerat delectus similique eius.",
                            FirstName = "Miguel Ángel",
                            LastName = "Medina",
                            PictureId = new Guid("2a964815-59b1-49b8-b3ad-6dc59dd9acf8"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("585c0152-1204-4258-a2d5-ddf114ddea21"),
                            Age = 14,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(1999, 9, 17, 17, 18, 23, 74, DateTimeKind.Utc).AddTicks(6384),
                            Description = "Numquam eum deserunt.",
                            FirstName = "Alfonso",
                            LastName = "Leyva",
                            PictureId = new Guid("64f8d0c1-86da-4efc-8fad-1d4f545daa35"),
                            HouseId = new Guid("7e8d6e4b-0aa5-4ffd-9707-41bc49c438dd")
                        },
                        new
                        {
                            Id = new Guid("9a8dcfd6-e2d5-44c6-998a-b507559be833"),
                            Age = 12,
                            BloodStatus = 2,
                            DateOfBirth = new DateTime(2005, 1, 16, 6, 11, 55, 481, DateTimeKind.Utc).AddTicks(4618),
                            Description = "Reprehenderit veritatis deserunt cum.",
                            FirstName = "Barbara",
                            LastName = "Torres",
                            PictureId = new Guid("10f0c552-2db8-4df1-beac-cf01d32af47e"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("5d61fc48-79d8-4f97-b957-a8ea31d926d7"),
                            Age = 13,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2007, 4, 11, 18, 29, 46, 510, DateTimeKind.Utc).AddTicks(5117),
                            Description = "Quo sint et eveniet fuga omnis nulla.",
                            FirstName = "Mariana",
                            LastName = "Lugo",
                            PictureId = new Guid("0163e086-1bb6-4cc9-baf5-8391a675acdf"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("d7c13968-3e86-4fb9-85b9-e96e568af9da"),
                            Age = 15,
                            BloodStatus = 4,
                            DateOfBirth = new DateTime(2008, 12, 2, 21, 10, 6, 891, DateTimeKind.Utc).AddTicks(2419),
                            Description = "Maiores voluptas id qui est.",
                            FirstName = "Eloisa",
                            LastName = "Avilés",
                            PictureId = new Guid("e8b34fde-2816-4264-b1aa-947029515186"),
                            HouseId = new Guid("0d046f3c-132c-4600-83c4-dc8ab34032b1")
                        },
                        new
                        {
                            Id = new Guid("37b719c7-5fa1-4f17-bce7-b25d4d0efcae"),
                            Age = 14,
                            BloodStatus = 3,
                            DateOfBirth = new DateTime(1997, 3, 23, 19, 38, 19, 582, DateTimeKind.Utc).AddTicks(1768),
                            Description = "Velit sequi dolores doloremque error odio voluptate.",
                            FirstName = "Sonia",
                            LastName = "Alaníz",
                            PictureId = new Guid("3daa51e5-934b-477c-a063-86654a15880d"),
                            HouseId = new Guid("9b2a78b1-dd4a-4543-a9d0-f3063ae5a8a9")
                        },
                        new
                        {
                            Id = new Guid("04a1a23f-8671-47d9-a70b-848e27f0fe98"),
                            Age = 15,
                            BloodStatus = 0,
                            DateOfBirth = new DateTime(2003, 10, 23, 3, 18, 49, 89, DateTimeKind.Utc).AddTicks(6916),
                            Description = "Similique soluta aut asperiores provident.",
                            FirstName = "Daniel",
                            LastName = "Apodaca",
                            PictureId = new Guid("683cc819-be69-43a7-b266-b599139cc1ca"),
                            HouseId = new Guid("ba18e1d7-82d6-4e6e-b17a-35e390ceec86")
                        });
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Primitives.Character", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Picture", "Picture")
                        .WithOne("Character")
                        .HasForeignKey("Hogwarts.Domain.Entities.Primitives.Character", "PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.StudentSubject", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogwarts.Domain.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Professor", "Professor")
                        .WithOne("Subject")
                        .HasForeignKey("Hogwarts.Domain.Entities.Subject", "ProfessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.Primitives.Character", null)
                        .WithOne()
                        .HasForeignKey("Hogwarts.Domain.Entities.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.HasOne("Hogwarts.Domain.Entities.House", "House")
                        .WithMany("Students")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hogwarts.Domain.Entities.Primitives.Character", null)
                        .WithOne()
                        .HasForeignKey("Hogwarts.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.House", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Picture", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Hogwarts.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
